#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C.UTF-8

# Bootstrap warning: detect pre-cutover state where ~/.claude/.pm is still a
# real directory. Warn but do not abort; canonical-path invocation still works.
if [ -e "$HOME/.claude/.pm" ] && [ ! -L "$HOME/.claude/.pm" ] && ! ps -o args= -p "${PPID:-0}" 2>/dev/null | grep -Fq 'pm/scripts/test/run-tests.sh'; then
  printf 'warn: %s is a real directory, not a symlink. Run install.sh to complete pm-schema cutover.\n' \
    "$HOME/.claude/.pm" >&2
fi

usage() {
  printf 'Usage: rollup.sh [--root <dir>] [--out <file>]\n' >&2
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
PM_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"

root="${HOME}/github"
out="$PM_ROOT/rollup/PORTFOLIO.md"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --root)
      if [ "$#" -lt 2 ]; then usage; exit 1; fi
      root=$2
      shift 2
      ;;
    --out)
      if [ "$#" -lt 2 ]; then usage; exit 1; fi
      out=$2
      shift 2
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

if [ ! -d "$root" ]; then
  printf 'rollup.sh: root not found: %s\n' "$root" >&2
  exit 1
fi

out_dir=$(dirname "$out")
mkdir -p "$out_dir"

data=$(mktemp)
tmp=$(mktemp "$out_dir/.PORTFOLIO.md.XXXXXX")
trap 'rm -f "$data" "$tmp"' EXIT

today=$(date +%Y-%m-%d)

# 掃描採用 schema marker 的 BACKLOG，未採用者安靜略過。
for backlog in "$root"/*/BACKLOG.md; do
  [ -f "$backlog" ] || continue
  if ! sed -n '1,5p' "$backlog" | grep -Eq '<!-- pm-schema: v1(\.1)? -->'; then
    continue
  fi
  repo=$(basename "$(dirname "$backlog")")
  awk -v repo="$repo" -v today="$today" '
  function trim(s) {
    gsub(/^[ \t\r\n]+/, "", s)
    gsub(/[ \t\r\n]+$/, "", s)
    return s
  }
  function leap(y) {
    return ((y % 4 == 0 && y % 100 != 0) || (y % 400 == 0))
  }
  function days_before_year(y, yy, d) {
    d = 0
    for (yy = 1970; yy < y; yy++) d += 365 + leap(yy)
    return d
  }
  function date_days(s, y, m, d, i, total) {
    y = substr(s, 1, 4) + 0
    m = substr(s, 6, 2) + 0
    d = substr(s, 9, 2) + 0
    md[1] = 31; md[2] = 28 + leap(y); md[3] = 31; md[4] = 30; md[5] = 31; md[6] = 30
    md[7] = 31; md[8] = 31; md[9] = 30; md[10] = 31; md[11] = 30; md[12] = 31
    total = days_before_year(y)
    for (i = 1; i < m; i++) total += md[i]
    return total + d
  }
  function parse_row(line, n, f, id, status, topic, area, refs, closed_date) {
    # Normalize escaped ASCII pipes before field split
    gsub(/\\[|]/, "｜", line)
    n = split(line, f, "|")
    if (n < 7) return
    id = trim(f[2])
    if (id !~ /^[A-Z][A-Z0-9]*-[0-9][0-9][0-9][a-z]*$/) return
    status = trim(f[3])
    topic = trim(f[4])
    area = trim(f[5])
    refs = trim(f[7])
    if (status == "🔵 active") {
      print "A\t" repo "\t" id "\t" topic "\t" area "\t" refs
    } else if (status ~ /^✅ closed [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$/) {
      closed_date = status
      sub(/^✅ closed /, "", closed_date)
      if (date_days(closed_date) >= date_days(today) - 30 && date_days(closed_date) <= date_days(today)) {
        print "C\t" repo "\t" id "\t" topic "\t" closed_date
      }
    }
  }
  { parse_row($0) }
  ' "$backlog" >> "$data"
done

# 統一從暫存資料產生 markdown，最後再原子搬移。
awk -v today="$today" '
BEGIN {
  FS = "\t"
}
{
  repo = $2
  if (!(repo in seen_repo)) {
    seen_repo[repo] = 1
    repo_order[++repo_count] = repo
  }
  if ($1 == "A") {
    active_count[repo]++
    active_repo[++active_n] = repo
    active_id[active_n] = $3
    active_topic[active_n] = $4
    active_area[active_n] = $5
    active_refs[active_n] = $6
  } else if ($1 == "C") {
    recent_count[repo]++
    recent_repo[++recent_n] = repo
    recent_id[recent_n] = $3
    recent_topic[recent_n] = $4
    recent_date[recent_n] = $5
  }
}
END {
  print "<!-- generated by rollup.sh on " today "; do not edit -->"
  print "# Portfolio rollup"
  print ""
  print "## Summary"
  print ""
  print "| Repo | Active | Recently closed (30d) |"
  print "|------|--------|-----------------------|"
  for (i = 1; i <= repo_count; i++) {
    repo = repo_order[i]
    print "| " repo " | " active_count[repo] + 0 " | " recent_count[repo] + 0 " |"
  }
  print ""
  print "## Active by repo"
  print ""
  for (i = 1; i <= repo_count; i++) {
    repo = repo_order[i]
    if ((active_count[repo] + 0) == 0) continue
    print "### " repo
    print "| # | 主題 | 影響面 | Refs |"
    print "|---|------|--------|------|"
    for (j = 1; j <= active_n; j++) {
      if (active_repo[j] == repo) {
        print "| " active_id[j] " | " active_topic[j] " | " active_area[j] " | " active_refs[j] " |"
      }
    }
    print ""
  }
  print "## Recently closed (last 30 days)"
  print ""
  print "| Repo | # | 主題 | Closed |"
  print "|------|---|------|--------|"
  for (i = 1; i <= recent_n; i++) {
    print "| " recent_repo[i] " | " recent_id[i] " | " recent_topic[i] " | " recent_date[i] " |"
  }
}
' "$data" > "$tmp"

mv "$tmp" "$out"
trap - EXIT
rm -f "$data"
