#!/usr/bin/env bash
# Sourceable adapter subcommands for pmctl.

if ! declare -F pmctl_die >/dev/null 2>&1; then
  pmctl_die() {
    printf 'pmctl: %s\n' "$*" >&2
    exit 2
  }
fi

pmctl_adapter_native_flags() {
  local name="$1" isolation_level="$2"

  case "$name/$isolation_level" in
    codex/none) printf '{}' ;;
    codex/read-only) printf '{ "--sandbox": "read-only" }' ;;
    codex/workspace-write) printf '{ "--sandbox": "workspace-write" }' ;;
    codex/workspace-network) printf '{ "--sandbox": "workspace-write", "-c": "sandbox_workspace_write.network_access=true" }' ;;
    codex/sandboxed) printf '{ "--sandbox": "workspace-write" }' ;;
    *) printf '{}' ;;
  esac
}

pmctl_adapter_generate() {
  local name="${1:-}"
  local adapter_dir executor_file isolation_file isolation_level native_flags

  [[ $# -eq 1 && -n "$name" ]] || pmctl_die "adapter generate requires <name>"

  if ! declare -F pmctl_validate_adapter_name >/dev/null; then
    pmctl_die "missing helper: pmctl_validate_adapter_name"
  fi
  if ! declare -F pmctl_write_new_file >/dev/null; then
    pmctl_die "missing helper: pmctl_write_new_file"
  fi
  if ! declare -F pmctl_policy_contains >/dev/null || ! declare -F pmctl_policy_values >/dev/null; then
    pmctl_die "missing helper: pmctl-policy"
  fi

  pmctl_validate_adapter_name "$name" || return 1

  adapter_dir="$REPO_ROOT/adapters/$name"
  executor_file="$REPO_ROOT/core/policy/executor-enum.yaml"
  isolation_file="$REPO_ROOT/core/policy/isolation-level.yaml"

  [[ -r "$executor_file" ]] || pmctl_die "missing: core/policy/executor-enum.yaml"
  [[ -r "$isolation_file" ]] || pmctl_die "missing: core/policy/isolation-level.yaml"
  pmctl_policy_contains "$executor_file" "$name" || pmctl_die "not in executor enum: $name"
  [[ -d "$adapter_dir" ]] && pmctl_die "adapter already exists: adapters/$name"

  mkdir -p "$adapter_dir"
  trap 'rm -rf "$adapter_dir" 2>/dev/null || true; trap - ERR' ERR

  pmctl_write_new_file "$adapter_dir/adapter.yaml" 0644 <<EOF
# adapter.yaml - AUTHORED manifest for adapters/$name/.
# This file is the source of truth. Do not add it to generated_files.
# pmctl regeneration must not edit this file.
# Required fields (8): schema_version, adapter_name, executor, cli_binary,
#   isolation_map_ref, runner_ref, dispatch_contract, generated_files
# Edit this file to configure the adapter; regenerate the other files with:
#   pmctl adapter generate $name  (will refuse to overwrite existing adapter)
schema_version: 1
adapter_name: $name
executor: $name
cli_binary: $name
isolation_map_ref: ./isolation-map.yaml
runner_ref: ./run.sh
dispatch_contract: dispatch_handover_v1
generated_files:
  - isolation-map.yaml
  - dispatch.sh
  - run.sh
  - README.md
EOF

  {
    printf '# adapters/%s/isolation-map.yaml\n' "$name"
    printf '# Generated by pmctl adapter generate %s.\n' "$name"
    printf '# Format: native_flags (flat CLI-flag map for new adapter starters).\n'
    printf '# NOTE: The pm-dispatch Codex runtime adapter (adapters/codex/isolation-map.yaml)\n'
    printf '# uses sandbox: + config_overrides: format (consumed by codex-dispatch.sh).\n'
    printf '# Edit generated files to match your executor'\''s actual CLI interface.\n\n'
    printf 'mappings:\n'
    while IFS= read -r isolation_level; do
      native_flags="$(pmctl_adapter_native_flags "$name" "$isolation_level")"
      printf '  %s:\n' "$isolation_level"
      if [[ "$name/$isolation_level" == "codex/sandboxed" ]]; then
        printf '    native_flags: %s  # best-effort: Codex has no full-isolation equivalent; treated as workspace-write\n' "$native_flags"
      elif [[ "$name/$isolation_level" == "codex/none" ]]; then
        printf '    native_flags: %s\n' "$native_flags"
        printf '    # intentional: isolation_level none means no restriction; no Codex isolation flag applied\n'
      else
        printf '    native_flags: %s\n' "$native_flags"
      fi
    done < <(pmctl_policy_values "$isolation_file")
  } | pmctl_write_new_file "$adapter_dir/isolation-map.yaml" 0644

  pmctl_write_new_file "$adapter_dir/run.sh" 0755 <<'EOF'
#!/usr/bin/env bash
# Generated by pmctl adapter generate. DO NOT EDIT.
set -euo pipefail

ADAPTER_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$ADAPTER_DIR/../.." && pwd)"

exec "$REPO_ROOT/cli/pmctl" dispatch run --adapter "$(basename "$ADAPTER_DIR")" "$@"
EOF

  # The executor entrypoint pmctl invokes (the shared flow resolves
  # adapters/<name>/dispatch.sh by convention). Scaffolded as a STUB so a freshly
  # generated adapter is reachable through `pmctl dispatch run` but fails loudly
  # until wired, rather than tripping an "unknown adapter" error for a missing file.
  pmctl_write_new_file "$adapter_dir/dispatch.sh" 0755 <<'EOF'
#!/usr/bin/env bash
# Generated by pmctl adapter generate — STUB. Wire your executor here.
#
# `pmctl dispatch run --adapter <name>` invokes this script with the dispatch
# flags (--cd, --brief-file, --model, --isolation, --timeout, --print-cmd, ...).
# A complete adapter MUST:
#   1. invoke the target executor against the brief, and
#   2. write the output contract — $WORK_DIR/.agent-trace/latest.last (the final
#      message) — so dispatch-post-verify.sh can read it.
# To activate the adapter you must also register its name in the dispatch
# allowlist (scripts/lib/executor-router.sh dispatch_route_for).
# See adapters/codex/dispatch.sh for a reference implementation.
set -euo pipefail
echo "adapter dispatch.sh stub: not yet wired to an executor — implement me" >&2
exit 2
EOF

  pmctl_write_new_file "$adapter_dir/README.md" 0644 <<EOF
# $name adapter

Generated by \`pmctl adapter generate $name\`.

\`adapter.yaml\` is the authored adapter manifest and source of truth; it is not listed in \`generated_files\`.

This adapter has two scripts:

- \`run.sh\` — the entrypoint users invoke; it execs \`pmctl dispatch run --adapter $name\` (the shared, validated + guarded dispatch flow).
- \`dispatch.sh\` — the executor glue pmctl calls. **Generated as a stub that exits non-zero** — implement it to invoke your executor and write the output contract (\`\$WORK_DIR/.agent-trace/latest.last\`). See \`adapters/codex/dispatch.sh\` for a reference.

To activate this adapter:

\`\`\`bash
# 1. implement adapters/$name/dispatch.sh (wire your executor)
# 2. register "$name" in the dispatch allowlist (scripts/lib/executor-router.sh dispatch_route_for)
bash "adapters/$name/run.sh" "\$@"
\`\`\`

Do not edit generated files listed in \`adapter.yaml\`.
To regenerate: delete \`adapters/$name/\` then rerun \`pmctl adapter generate $name\`.
EOF

  trap - ERR
  printf 'pmctl: generated adapter %s at %s\n' "$name" "${adapter_dir#$REPO_ROOT/}"
}

export -f pmctl_adapter_native_flags
export -f pmctl_adapter_generate
