#!/usr/bin/env bash
# Sourceable adapter subcommands for pmctl.

if ! declare -F pmctl_die >/dev/null 2>&1; then
  pmctl_die() {
    printf 'pmctl: %s\n' "$*" >&2
    exit 2
  }
fi

pmctl_adapter_native_flags() {
  local name="$1" isolation_level="$2"

  case "$name/$isolation_level" in
    codex/none) printf '{ "--sandbox": "danger-full-access" }' ;;
    codex/read-only) printf '{ "--sandbox": "read-only" }' ;;
    codex/workspace-write) printf '{ "--sandbox": "workspace-write" }' ;;
    codex/sandboxed) printf '{ "--sandbox": "workspace-write" }' ;;
    *) printf '{}' ;;
  esac
}

pmctl_adapter_generate() {
  local name="${1:-}"
  local adapter_dir executor_file isolation_file isolation_level native_flags

  [[ $# -eq 1 && -n "$name" ]] || pmctl_die "adapter generate requires <name>"

  if ! declare -F pmctl_validate_adapter_name >/dev/null; then
    pmctl_die "missing helper: pmctl_validate_adapter_name"
  fi
  if ! declare -F pmctl_write_new_file >/dev/null; then
    pmctl_die "missing helper: pmctl_write_new_file"
  fi
  if ! declare -F pmctl_policy_contains >/dev/null || ! declare -F pmctl_policy_values >/dev/null; then
    pmctl_die "missing helper: pmctl-policy"
  fi

  pmctl_validate_adapter_name "$name" || return 1

  adapter_dir="$REPO_ROOT/adapters/$name"
  executor_file="$REPO_ROOT/core/policy/executor-enum.yaml"
  isolation_file="$REPO_ROOT/core/policy/isolation-level.yaml"

  [[ -r "$executor_file" ]] || pmctl_die "missing: core/policy/executor-enum.yaml"
  [[ -r "$isolation_file" ]] || pmctl_die "missing: core/policy/isolation-level.yaml"
  pmctl_policy_contains "$executor_file" "$name" || pmctl_die "not in executor enum: $name"
  [[ -d "$adapter_dir" ]] && pmctl_die "adapter already exists: adapters/$name"

  mkdir -p "$adapter_dir"
  trap 'rm -rf "$adapter_dir" 2>/dev/null || true; trap - ERR' ERR

  pmctl_write_new_file "$adapter_dir/adapter.yaml" 0644 <<EOF
schema_version: 1
adapter_name: $name
executor: $name
cli_binary: $name
isolation_map_ref: ./isolation-map.yaml
runner_ref: ./run.sh
dispatch_contract: dispatch_handover_v1
generated_files:
  - isolation-map.yaml
  - run.sh
  - README.md
EOF

  {
    printf '# adapters/%s/isolation-map.yaml\n' "$name"
    printf '# Generated by pmctl adapter generate %s.\n\n' "$name"
    printf 'mappings:\n'
    while IFS= read -r isolation_level; do
      native_flags="$(pmctl_adapter_native_flags "$name" "$isolation_level")"
      printf '  %s:\n' "$isolation_level"
      printf '    native_flags: %s\n' "$native_flags"
    done < <(pmctl_policy_values "$isolation_file")
  } | pmctl_write_new_file "$adapter_dir/isolation-map.yaml" 0644

  pmctl_write_new_file "$adapter_dir/run.sh" 0755 <<'EOF'
#!/usr/bin/env bash
# Generated by pmctl adapter generate. DO NOT EDIT.
set -euo pipefail

ADAPTER_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$ADAPTER_DIR/../.." && pwd)"

exec "$REPO_ROOT/cli/pmctl" dispatch run --adapter "$(basename "$ADAPTER_DIR")" "$@"
EOF

  pmctl_write_new_file "$adapter_dir/README.md" 0644 <<EOF
# $name adapter

Generated by \`pmctl adapter generate $name\`.

Wire the target CLI command surface to execute:

\`\`\`bash
bash "adapters/$name/run.sh" "\$@"
\`\`\`

Do not edit generated files listed in \`adapter.yaml\`; regenerate them with \`pmctl adapter generate $name\`.
EOF

  trap - ERR
  printf 'pmctl: generated adapter %s at %s\n' "$name" "${adapter_dir#$REPO_ROOT/}"
}

export -f pmctl_adapter_native_flags
export -f pmctl_adapter_generate
